
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.117.120:3306/steam?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: milk
    password: milk
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
  redis:
    username: fortice
    password: redis6379
    port: 6379
    host: 54.180.117.120
    lettuce:
      shutdown-timeout: 100ms
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: steam
      username: milk
      password: milk
logging:
  file:
    path: ~/payment_log
    max-size: 10MB
    max-history: 10
  level:
    root: info
    com.steam.paymen: debug