milk:
  kakaopay:
    api-url: https://kapi.kakao.com/v1/payment/
    cid: TC0ONETIME
    url:
      approval: http://localhost:3000/charge/approval
      cancel: http://localhost:3000/charge/cancel
      fail: http://localhost:3000/charge/fail
    access-token: a778c6b16a64af02435c862926fe1b44

server:
  port: 8200
spring:
  profiles:
    active: local