
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/steam?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: milk
    password: milk
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
  redis:
    port: 6379
    host: localhost
    lettuce:
      shutdown-timeout: 100ms
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: steam
      database: steam
      username: milk
      password: milk
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  file:
    path: /home/fortice/payment_log
    max-size: 10MB
    max-history: 10
  level:
    root: info
    com.steam.payment: debug