spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.117.120:3306/steam?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: milk
    password: milk
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
  redis:
    port: 6379
    host: 54.180.117.120
    lettuce:
      shutdown-timeout: 100ms
  rabbitmq:
    host: 3.35.0.63
    port: 5672
    username: fortice
    password: rhksflwk123@
    virtual-host: /robby
    stream:
      host: 3.35.0.63
      port: 5672
      username: fortice
      password: rhksflwk123@

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

