
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/steam?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: milk
    password: milk
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
  redis:
    port: 6379
    host: localhost
    lettuce:
      shutdown-timeout: 100ms
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /lobby
    password: rhksflwk123@
    username: fortice

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.steam.library: debug
    root: info
  file:
    path: /home/fortice/library_log/
    name: library.log