logging:
  level:
    com.steam.gateway: debug

server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: false
            postLogger: false
      routes:
        - id: auth-svc
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
        - id: grpc-svc
          uri: http://localhost:8100/
          predicates:
            - Path=/store/**
        - id: chat-ws-svc
          uri: ws://localhost:8102/
          predicates:
            - Path=/chat/**
        - id: chat-http-svc
          uri: http://localhost:8102/
          predicates:
            - Path=/chat/info/**
        - id: payment-svc
          uri: http://localhost:8200/
          predicates:
            - Path=/payment/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Spring Cloud Gateway AuthorizationCheckFilter
        - id: membership-svc
          uri: http://localhost:8201/
          predicates:
            - Path=/membership/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Membership AuthorizationCheckFilter
        - id: robby-http-svc
          uri: http://localhost:8210/
          predicates:
            - Path=/library/info/**
        - id: robby-ws-svc
          uri: ws://localhost:8210/
          predicates:
            - Path=/library/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH