logging:
  level:
    com.steam.gateway: trace

server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: auth-svc
          uri: http://auth:8081/
          predicates:
            - Path=/auth/**
        - id: grpc-svc
          uri: http://grpc_gateway:8100/
          predicates:
            - Path=/store/**
        - id: payment-svc
          uri: http://payment:8200/
          predicates:
            - Path=/payment/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Payment AuthorizationCheckFilter
        - id: membership-svc
            uri: http://membership:8201/
            predicates:
              - Path=/membership/**
            filters:
              - name: AuthorizationCheckFilter
                args:
                  baseMessage: Membership AuthorizationCheckFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH