logging:
  level:
    com.steam.gateway: debug

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defalutZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: auth-svc
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: grpc-gateway
          uri: lb://GRPC-GATEWAY
          predicates:
            - Path=/store/**
        - id: chat-ws-svc
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
        - id: chat-http-svc
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/info/**
        - id: payment-svc
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Spring Cloud Gateway AuthorizationCheckFilter
        - id: membership-svc
          uri: lb://MEMBERSHIP-SERVICE
          predicates:
            - Path=/membership/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Membership AuthorizationCheckFilter
        - id: robby-http-svc
          uri: lb://ROBBY-SERVICE
          predicates:
            - Path=/library/info/**
        - id: robby-ws-svc
          uri: lb://ROBBY-SERVICE
          predicates:
            - Path=/library/**