logging:
  level:
    com.steam.gateway: debug

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defalutZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: auth-svc
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: grpc-gateway
          uri: http://localhost:8100
          predicates:
            - Path=/store/**
        - id: chat-ws-svc
          uri: ws://localhost:8102/
          predicates:
            - Path=/chat/**
        - id: chat-http-svc
          uri: http://localhost:8102/
          predicates:
            - Path=/chat/info/**
        - id: payment-svc
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Spring Cloud Gateway AuthorizationCheckFilter
        - id: membership-svc-auth-check-friend
          uri: lb://MEMBERSHIP-SERVICE
          predicates:
            - Path=/membership/friends/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Membership AuthorizationCheckFilter
        - id: membership-svc-auth-check-friend-request
          uri: lb://MEMBERSHIP-SERVICE
          predicates:
            - Path=/membership/friend-requests/**
          filters:
            - name: AuthorizationCheckFilter
              args:
                baseMessage: Membership AuthorizationCheckFilter
        - id: membership-svc-no-auth
          uri: lb://MEMBERSHIP-SERVICE
          predicates:
            - Path=/membership/**
        - id: robby-http-svc
          uri: lb://ROBBY-SERVICE
          predicates:
            - Path=/library/info/**
        - id: robby-ws-svc
          uri: lb://ROBBY-SERVICE
          predicates:
            - Path=/library/**