server:
    port: 8761

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 500
    serviceUrl:
        defaultZone: http://localhost:8761